### Site metadata

title: VoxTour Support
description: VoxTour.ai Support Pages
lang: en

### Build settings

url: https://support.voxtour.ai
baseurl: ""

theme: just-the-docs

plugins:
  - jekyll-polyglot
  - jekyll-seo-tag

languages: ["en", "ru", "he", "es", "fr", "it"]
default_lang: "en"
default_lang_in_subdir: false
exclude_from_localization:
  - assets
  - CNAME
  - sitemap.xml
  - robots.txt
parallel_localization: false

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - README.md
  - planning
  - tour

search_enabled: true

color_scheme: voxtourai

logo: "/assets/images/logo.png"

aux_links:
  "Voxtour.ai":
    - "//voxtour.ai"

collections:
  general_information:
    output: true
    permalink: /help-center/general-information/:title/
  user_guide:
    output: true
    permalink: /help-center/user-guide/:title/
  features_overview:
    output: true
    permalink: /help-center/features-overview/:title/
  account_management:
    output: true
    permalink: /help-center/account-management/:title/
  settings:
    output: true
    permalink: /help-center/settings/:title/
  apis:
    output: true
    permalink: /api/references/:title/
